#!/usr/bin/env python3
"""Generate STATUS.md from logs/runs-*.jsonl + seen.json.

Called by orchestrator at the end of each run:
    python3 scripts/gen_status.py > STATUS.md

Outputs a markdown report:
- Last run summary (status, videos, duration, tokens)
- Recent runs table (last 10)
- Backlog estimate (latest watcher's "found X new" minus processed)
- Per-channel state (total processed)
- Telegram failure banner if detected in latest run

No external dependencies — stdlib only.
"""
import json
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

# Local utility import (sibling file)
sys.path.insert(0, str(Path(__file__).resolve().parent))
from utils import all_log_files, ROOT, SEEN  # noqa: E402


def parse_runs():
    """Read all logs/runs-*.jsonl files and group entries by run_id."""
    runs = defaultdict(list)
    for log_file in all_log_files():
        for line in log_file.read_text().splitlines():
            if not line.strip():
                continue
            try:
                e = json.loads(line)
                runs[e.get("run_id", "unknown")].append(e)
            except json.JSONDecodeError:
                continue
    return runs


def summarize(entries):
    """Compute summary stats for one run."""
    if not entries:
        return None
    by_ts = sorted(entries, key=lambda e: e.get("ts", ""))
    start_ts = by_ts[0].get("ts", "")
    end_ts = by_ts[-1].get("ts", "")

    processed = sum(
        1 for e in entries if e.get("agent") == "extractor" and e.get("status") == "ok"
    )
    errors = sum(1 for e in entries if e.get("status") == "error")
    tokens = sum(
        int(e.get("tokens_in", 0) or 0) + int(e.get("tokens_out", 0) or 0)
        for e in entries
    )

    try:
        s = datetime.fromisoformat(start_ts.replace("Z", "+00:00"))
        en = datetime.fromisoformat(end_ts.replace("Z", "+00:00"))
        duration_s = (en - s).total_seconds()
    except (ValueError, AttributeError):
        duration_s = 0

    if errors == 0 and processed > 0:
        status = "✅ ok"
    elif errors > 0 and processed > 0:
        status = "⚠️ partial"
    elif errors > 0:
        status = "🚨 fail"
    else:
        status = "💤 idle"

    # Backlog: watcher entries log "found K new of T total"
    found_per_channel = {}
    for e in entries:
        if e.get("agent") == "watcher" and e.get("status") == "ok":
            notes = e.get("notes", "")
            try:
                k = int(notes.split("found ")[1].split(" ")[0])
                if k > 0:
                    found_per_channel[e["channel"]] = k
            except (IndexError, ValueError):
                pass

    return {
        "run_id": entries[0].get("run_id", "?"),
        "start": start_ts,
        "processed": processed,
        "errors": errors,
        "duration_s": duration_s,
        "tokens": tokens,
        "status": status,
        "found_per_channel": found_per_channel,
    }


def fmt_duration(s):
    if s < 1:
        return "—"
    if s < 60:
        return f"{int(s)}s"
    m, sec = int(s // 60), int(s % 60)
    if m < 60:
        return f"{m}m{sec:02d}s"
    h = m // 60
    return f"{h}h{m % 60:02d}m"


def fmt_tokens(t):
    if t == 0:
        return "—"
    if t < 1000:
        return str(t)
    if t < 1_000_000:
        return f"{t / 1000:.0f}k"
    return f"{t / 1_000_000:.1f}M"


def fmt_cost(tokens):
    """Rough cost estimate at Claude Sonnet 4.x API prices ($3/MTok in, $15/MTok out).
    Assume 60/40 in/out split. Returns dollars rounded to 2 decimals.

    Note: this estimate is only meaningful if the user is on the ANTHROPIC_API_KEY
    (pay-as-you-go) path. On the ANTHROPIC_TOKEN (claude.ai subscription) path,
    there's no per-call billing — the figure is purely informational
    (approximate API-equivalent burn against subscription quota).
    """
    if tokens == 0:
        return "—"
    tokens_in = tokens * 0.6
    tokens_out = tokens * 0.4
    cost = (tokens_in / 1_000_000) * 3 + (tokens_out / 1_000_000) * 15
    if cost < 0.01:
        return "<$0.01"
    return f"~${cost:.2f}"


def main():
    runs = parse_runs()
    sorted_ids = sorted(runs.keys(), reverse=True)

    out = []
    out.append("# youtube-radar status")
    out.append("")
    out.append(
        "_Auto-generated by orchestrator at the end of each run. "
        "Do not edit manually — overwritten on next run._"
    )
    out.append("")
    out.append(f"_Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_")
    out.append("")

    if sorted_ids:
        latest = summarize(runs[sorted_ids[0]])
        out.append(
            f"**Last run:** `{sorted_ids[0]}` · {latest['status']} · "
            f"{latest['processed']} videos · {fmt_duration(latest['duration_s'])} · "
            f"{fmt_tokens(latest['tokens'])} tokens ({fmt_cost(latest['tokens'])})"
        )

        # Critical alert banner: detect Telegram failures in latest run.
        # (alert mechanism uses the same bot token, so if broken, alerts also silent)
        tg_fails = [
            e
            for e in runs[sorted_ids[0]]
            if e.get("agent") == "notifier"
            and e.get("status") == "error"
            and "TELEGRAM" in (e.get("notes") or "").upper()
        ]
        if tg_fails:
            out.append("")
            out.append(
                "> 🚨 **TELEGRAM DELIVERY FAILED** — the last run did not send "
                f"{len(tg_fails)} messages. This includes failure alerts (single "
                "point of failure: alerts use the same bot token). Verify "
                "`TELEGRAM_BOT_TOKEN` in env vars — typical causes: revoked, "
                "wrong copy, trailing whitespace. Without this fix all future "
                "runs will deliver nowhere."
            )
    else:
        out.append("**No runs logged yet.**")
    out.append("")

    # Aggregate stats
    if sorted_ids:
        total_processed = sum(summarize(runs[rid])["processed"] for rid in sorted_ids)
        total_tokens = sum(summarize(runs[rid])["tokens"] for rid in sorted_ids)
        total_runs = len(sorted_ids)
        out.append("## Aggregate")
        out.append("")
        out.append(f"- **Runs total:** {total_runs}")
        out.append(f"- **Videos processed all-time:** {total_processed}")
        out.append(
            f"- **Tokens consumed (estimate):** {fmt_tokens(total_tokens)} "
            f"≈ {fmt_cost(total_tokens)}"
        )
        out.append("")

    out.append("## Recent runs (last 10)")
    out.append("")
    out.append("| Run ID | Status | Videos | Errors | Duration | Tokens | Cost |")
    out.append("|---|---|---|---|---|---|---|")
    for rid in sorted_ids[:10]:
        s = summarize(runs[rid])
        if s:
            out.append(
                f"| `{rid}` | {s['status']} | {s['processed']} | {s['errors']} | "
                f"{fmt_duration(s['duration_s'])} | {fmt_tokens(s['tokens'])} | "
                f"{fmt_cost(s['tokens'])} |"
            )
    out.append("")

    out.append("## Backlog (latest watcher)")
    out.append("")
    if sorted_ids:
        latest = summarize(runs[sorted_ids[0]])
        total_found = sum(latest["found_per_channel"].values())
        if total_found > latest["processed"]:
            backlog = total_found - latest["processed"]
            out.append(
                f"The latest watcher found **{total_found}** new videos; "
                f"**{latest['processed']}** were processed (quota 5/run). "
                f"**Backlog: {backlog} videos** wait for future runs."
            )
            out.append("")
            out.append("| Channel | New found |")
            out.append("|---|---|")
            for ch, n in sorted(
                latest["found_per_channel"].items(), key=lambda x: -x[1]
            ):
                out.append(f"| `{ch}` | {n} |")
        elif total_found == 0:
            out.append("No new videos found in the latest watcher run.")
        else:
            out.append(
                f"No backlog — watcher found {total_found} new, "
                f"{latest['processed']} processed."
            )
    else:
        out.append("No watcher data yet — runs.jsonl is empty.")
    out.append("")

    out.append("## Per-channel state")
    out.append("")
    out.append("| Channel | Processed total |")
    out.append("|---|---|")
    if SEEN.exists():
        seen = json.loads(SEEN.read_text())
        for ch, ids in sorted(seen.items()):
            count = len(ids) if isinstance(ids, list) else 0
            out.append(f"| `{ch}` | {count} |")
    else:
        out.append("| _seen.json not found_ | — |")
    out.append("")

    print("\n".join(out))


if __name__ == "__main__":
    main()
